version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    depends_on:
      - jsonserver

  jsonserver:
    build:
      context: .
      dockerfile: Dockerfile.jsonserver
    ports:
      - "4000:4000"
